### ISSUE TITLE
Server is not tolerant of RabbitMQ failures

### ISSUE THREAD

**Issue by Xyene** [DMOJ/event-server#3]
```
amqp connection error... Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/code/event-server/node_modules/ws/lib/websocket.js:332:19)
    at WebSocket.socket.got_message (/code/event-server/event.js:115:20)
    at /code/event-server/event.js:65:24
    at exports.Set.each (/code/event-server/node_modules/simplesets/lib/simplesets.js:142:6)
    at /code/event-server/event.js:64:23
    at Message.<anonymous> (/code/event-server/node_modules/amqp/lib/queue.js:209:28)
    at Message.emit (events.js:223:5)
    at Queue._onContent (/code/event-server/node_modules/amqp/lib/queue.js:550:25)
    at AMQPParser.self.parser.onContent (/code/event-server/node_modules/amqp/lib/connection.js:142:32)
    at frameEnd (/code/event-server/node_modules/amqp/lib/parser.js:101:18)
```

**Comment by Xyene** [comment]
"Fixed" in https://github.com/DMOJ/event-server/commit/20122d62d3449a2ef4a7545af6c7d65e7f2b72f4.
